/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'obushi' at '16/09/14 21:49' with Gradle 2.13
 *
 * @author obushi, @date 16/09/14 21:49
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
