import static org.junit.Assert.*;

import org.junit.Test;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'obushi' at '16/09/14 21:49' with Gradle 2.13
 *
 * @author obushi, @date 16/09/14 21:49
 */
public class LibraryTest {
    @Test
    public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
